Adjusted default port to match with k2 defaults
eHealthExperts/k2-basecamp pull request #28
Opened 2018-06-15 11:12 UTC by maxmartens

2018-07-13 23:00 UTC, tumbl3w33d requested changes
Find ich gut, aber du musst die Tests noch anpassen. Da hat es im CI gekracht.

2018-07-14 06:18 UTC, ChriFo submitted a review, later dismissed

2018-07-14 06:19 UTC, ChriFo commented
Mit https://github.com/eHealthExperts/k2-basecamp/pull/27 und einem Merge vom master in diesen PR kann dieser dann angenommen werden!

2018-07-14 12:00 UTC, ChriFo commented
uhh @tumbl3w33d  hat Recht: in `settings.rs` Zeile 177 muss der Port noch angepasst werden.

2018-07-16 09:40 UTC, tumbl3w33d submitted a review, later dismissed

2018-07-16 10:54 UTC, tumbl3w33d commented
6 commits für 6 veränderte LOC. :grin: Der @ChriFo darf als Schirmherr dann entscheiden, ob er das noch gesquasht haben möchte oder es so in die history darf.

2018-07-17 13:27 UTC, ChriFo approved these changes

2018-07-17 13:28 UTC, merged